### ISSUE TITLE
Help: What am I doing wrong?

### ISSUE THREAD

**Issue by steakscience** [sergeysolovev/react-hyphen#26]
Hi,
I'm currently trying to use this with my Gatsby project. This is how I'm using it:

```
import React from "react"
import Hyphenated from "react-hyphen"
```

```
<Hyphenated>
      <section dangerouslySetInnerHTML={{ __html: post.html }} />
</Hyphenated>
```

But it doesn't seem to do anything. Which part am I doing wrong?

**Comment by sergeysolovev** [comment]
@steakscience it should work fine with `dangerouslySetInnerHTML`. Please check out this example: https://codesandbox.io/s/react-hyphen-dangerously-set-inner-html-nt1ub

**Comment by sergeysolovev** [comment]
@steakscience thank you for your feedback. True, `dangerouslySetInnerHTML` hasn’t been supported until now. Please install `v1.4.0` and check it.

Just in case, here is an example of how it should work: https://codesandbox.io/s/react-hyphen-dangerously-set-inner-html-nt1ub

**Comment by steakscience** [comment]
@sergeysolovev Thank you! 🙏

**Comment by sergeysolovev** [comment]
@steakscience You are welcome!
